package com.beegrinder.sw5e.modulegenerator;

import java.util.HashMap;
import java.util.Map;

public class AppActionOverride {

	private static final Map<String, String> actionOverrideMap = new HashMap<>() {
		{
			put("Acid Wind","<actions/>");
			put("Acidic Strike","<actions/>");
			put("Armor of Abeloth","<actions/>");
			put("Autonomous Servant","<actions/>");
			put("Bacta Pack","<actions/>");
			put("Battle Insight","<actions/>");
			put("Beacon of Hope","<actions/>");
			put("Bestow Curse","<actions/>");
			put("Bestow Virus","<actions/>");
			put("Buffer","<actions/>");
			put("Call Lightning","<actions/>");
			put("Capacity Boost","<actions/>");
			put("Carbon Fog","<actions/>");
			put("Carbonite Explosion","<actions/>");
			put("Combustive Shot","<actions/>");
			put("Comprehend Speech","<actions/>");
			put("Concealed Caltrops","<actions/>");
			put("Condense/Vaporize","<actions/>");
			put("Control Pain","<actions/>");
			put("Copy","<actions/>");
			put("Countermeasures","<actions/>");
			put("Cryogenic Wave","<actions/>");
			put("Dark Aura","<actions/>");
			put("Decryption Program","<actions/>");
			put("Defibrillate","<actions/>");
			put("Destroy Tech","<actions/>");
			put("Dun Moch","<actions/>");
			put("Echo Blast","<actions/>");
			put("Elemental Accelerant","<actions/>");
			put("Energetic Burst","<actions/>");
			put("Enhance Droid","<actions/>");
			put("Execute Command","<actions/>");
			put("Extinguish","<actions/>");
			put("Fabricate Trap","<actions/>");
			put("Flash","<actions/>");
			put("Force Blinding","<actions/>");
			put("Force Blur","<actions/>");
			put("Force Concealment","<actions/>");
			put("Force Focus","<actions/>");
			put("Force Imbuement","<actions/>");
			put("Force Leap","<actions/>");
			put("Force Mask","<actions/>");
			put("Force Meld","<actions/>");
			put("Force Propel","<actions/>");
			put("Force Reflect","<actions/>");
			put("Force Repulse","<actions/>");
			put("Force Shunt","<actions/>");
			put("Force Throw","<actions/>");
			put("Force Vision","<actions/>");
			put("Force Weapon","<actions/>");
			put("Force Whisper","<actions/>");
			put("Frequency Scan","<actions/>");
			put("Friendly Fire","<actions/>");
			put("Glide","<actions/>");
			put("Greater Analyze","<actions/>");
			put("Greater Heal","<actions/>");
			put("Greater Hologram","<actions/>");
			put("Greater Saber Throw","<actions/>");
			put("Greater Translation Program","<actions/>");
			put("Group Hologram","<actions/>");
			put("Hallucination","<actions/>");
			put("Haywire","<actions/>");
			put("Heroism","<actions/>");
			put("Holding Cell","<actions/>");
			put("Hologram","<actions/>");
			put("Holographic Disguise","<actions/>");
			put("Homing Rockets","<actions/>");
			put("Hysteria","<actions/>");
			put("Illusory Strike","<actions/>");
			put("Illusory Terrain","<actions/>");
			put("Improved Force Barrier","<actions/>");
			put("Improved Phasewalk","<actions/>");
			put("Improved Restoration","<actions/>");
			put("Improved Saber Throw","<actions/>");
			put("Ionic Strike","<actions/>");
			put("Kolto Dispenser","<actions/>");
			put("Magnetic Field","<actions/>");
			put("Magnetic Hold","<actions/>");
			put("Malacia","<actions/>");
			put("Mass Animation","<actions/>");
			put("Mass Hysteria","<actions/>");
			put("Mass Malacia","<actions/>");
			put("Master Force Barrier","<actions/>");
			put("Master Malacia","<actions/>");
			put("Master Saber Throw","<actions/>");
			put("Mind Prison","<actions/>");
			put("Mind Trap","<actions/>");
			put("Minor Defibrillation","<actions/>");
			put("Minor Hologram","<actions/>");
			put("Morichro","<actions/>");
			put("Motivator Boost","<actions/>");
			put("Necrotic Charge","<actions/>");
			put("Necrotic Touch","<actions/>");
			put("Neurotoxin","<actions/>");
			put("Override Interface","<actions/>");
			put("Phasewalk","<actions/>");
			put("Pheromone Burst","<actions/>");
			put("Poison Dart","<actions/>");
			put("Predictive AI","<actions/>");
			put("Pressure Crush","<actions/>");
			put("Project Hologram","<actions/>");
			put("Psychic Charge","<actions/>");
			put("Psychometry","<actions/>");
			put("Radiation","<actions/>");
			put("Read Memory","<actions/>");
			put("Reboot","<actions/>");
			put("Rebuke","<actions/>");
			put("Remove Curse","<actions/>");
			put("Remove Virus","<actions/>");
			put("Reprogram Droid","<actions/>");
			put("Restoration","<actions/>");
			put("Rewrite Memory","<actions/>");
			put("Rime Shot","<actions/>");
			put("Scan Area","<actions/>");
			put("Scramble Interface","<actions/>");
			put("Scrambling Barrier","<actions/>");
			put("Security Protocols","<actions/>");
			put("Seethe","<actions/>");
			put("Shadow Sight","<actions/>");
			put("Shocking Ray","<actions/>");
			put("Short Circuit","<actions/>");
			put("Skill Protocol","<actions/>");
			put("Smoke Cloud","<actions/>");
			put("Sonic Charge","<actions/>");
			put("Sonic Fists","<actions/>");
			put("Sonic Shot","<actions/>");
			put("Sonic Strike","<actions/>");
			put("Sound Trick","<actions/>");
			put("Spectrum Bolt","<actions/>");
			put("Spectrum Ray","<actions/>");
			put("Spirit Blade","<actions/>");
			put("Stun Dart","<actions/>");
			put("Superior Translation Program","<actions/>");
			put("Sustained Lightning","<actions/>");
			put("Targeting Shot","<actions/>");
			put("Telekinetic Shield","<actions/>");
			put("Telekinetic Storm","<actions/>");
			put("Telemetry","<actions/>");
			put("Tonal Translocate","<actions/>");
			put("Translation Program","<actions/>");
			put("True Sight","<actions/>");
			put("Truth Serum","<actions/>");
			put("Venomous Strike","<actions/>");
			put("Vertical Maneuvering","<actions/>");
			put("Voltaic Shielding","<actions/>");
			put("Vortex Shot","<actions/>");
			put("Warding Shot","<actions/>");
			put("Will of the Force","<actions/>");
			put("Wire Bind","<actions/>");
			put("Wire Line","<actions/>");
			put("Wrack","<actions/>");
		}
		
		
	};

	public static Map<String, String> getActionOverrideMap() {
		return actionOverrideMap;
	}

}
